const fs=require("fs/promises"),path=require("path"),{spawn}=require("child_process"),config=require("./config");
const BLOCKED=[/\brm\s+-rf\s+\/(?:\s|$)/i,/\brm\s+-rf\s+~(?:\s|$)/i,/\bmkfs(?:\s|$)/i,/\bdd\s+if=.*of=\/dev\//i,/\bshutdown(?:\s|$)/i,/\breboot(?:\s|$)/i,/\bpoweroff(?:\s|$)/i];
const NETWORK=/\b(curl|wget|ssh|scp|nc|netcat)\b|git\s+(clone|fetch|pull|push)|npm\s+(install|i|update)|pip\s+install/i;
function safe(p="."){const t=path.resolve(config.workspace,p),b=config.workspace+path.sep;if(t!==config.workspace&&!t.startsWith(b))throw new Error("Path escapes workspace");return t}
async function tree(){const o=[];async function w(d,n){if(n>4||o.length>=500)return;for(const e of await fs.readdir(d,{withFileTypes:true})){if(["node_modules",".git",".cache","__pycache__",".agent"].includes(e.name))continue;const f=path.join(d,e.name),r=path.relative(config.workspace,f);o.push(e.isDirectory()?r+"/":r);if(e.isDirectory())await w(f,n+1)}}await w(config.workspace,0);return o}
async function read(p){const f=safe(p),s=await fs.stat(f);if(s.size>config.maxFileBytes)throw new Error(`File exceeds ${config.maxFileBytes} bytes`);return fs.readFile(f,"utf8")}
async function write(p,c){const f=safe(p);await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f,c,"utf8");return`wrote ${path.relative(config.workspace,f)}`}
async function patch(p,a,b){const f=safe(p),c=await fs.readFile(f,"utf8"),n=c.split(a).length-1;if(n!==1)throw new Error(`Patch expected exactly one match; found ${n}`);await fs.writeFile(f,c.replace(a,b),"utf8");return`patched ${path.relative(config.workspace,f)}`}
async function search(p){const rx=new RegExp(p,"i"),hits=[];for(const r of await tree()){if(r.endsWith("/"))continue;try{(await fs.readFile(safe(r),"utf8")).split("\n").forEach((l,i)=>{if(rx.test(l))hits.push(`${r}:${i+1}: ${l.slice(0,400)}`)})}catch{}if(hits.length>=150)break}return hits}
function exec(command){return new Promise((resolve,reject)=>{if(BLOCKED.some(r=>r.test(command)))return reject(new Error("Blocked destructive command"));if(!config.allowNetwork&&NETWORK.test(command))return reject(new Error("Network/package command blocked; set ALLOW_NETWORK=true"));const c=spawn("sh",["-lc",command],{cwd:config.workspace,env:process.env});let out="",err="",to=false;const t=setTimeout(()=>{to=true;c.kill("SIGTERM")},config.commandTimeoutMs);c.stdout.on("data",d=>out+=d);c.stderr.on("data",d=>err+=d);c.on("error",e=>{clearTimeout(t);reject(e)});c.on("close",code=>{clearTimeout(t);resolve({code,timeout:to,stdout:out.slice(-15000),stderr:err.slice(-15000)})})})}
async function git(command){if(!["status --short","branch --show-current","diff --stat","diff","log -5 --oneline"].includes(command))throw new Error("Only read-only git commands allowed");return exec(`git ${command}`)}
module.exports={tree,read,write,patch,search,exec,git};
